### ISSUE TITLE
Could the bundle.js provide some interfaces/functions we can use?

### ISSUE THREAD

**Issue by chaitd** [geopamplona/olgm-webpack#1]
我已经做出了bundle.js，但是这个js有没有接口暴露出来让我能用呢？我看这个js好像是个闭包，这样我就没法用olgm里的方法了呀。 是我没发现怎么用么？你可以提供一个使用其中功能的demo吗？比如使用 `new GoogleLayer();`
求助~多谢！
I have generated a bundle.js by your project. But I find that ths js has no interfaces or functions I can use. Does it have? The bundle.js looks like a closure, thus I cann't use functions olgm provides. 
Could you provide a demo which use funcitons in olgm? For example `new GoogleLayer();`

Could you help me? Thank you very much.

**Comment by geopamplona** [comment]
This repository is an example of how to integrate olgm with webpack.
If you want to modify the functionality, you can do it in the main.js file or adapting it to your needs or project.
Once the bundle.js is compiled, you can see the example running in the browser by opening the index.html file
